global:
    scrape_interval:     5s
    evaluation_interval: 5s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"
  
  # A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
    - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
      static_configs:
      - targets: ['nginx','prometheus:9090']

# scrape_configs:
    - job_name: cadvisor
      scrape_interval: 5s
      static_configs:
      - targets:
        - cadvisor:8080

    - job_name: node_exporter
      scrape_interval: 5s
      static_configs:
      - targets:
        - node_exporter:9100

    - job_name: grafana
      scrape_interval: 5s
      static_configs:
      - targets:
        - grafana:3000

