# Generated by Django 3.1 on 2020-12-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='admission_mode_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='no_of_backlogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='education',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
