# Generated by Django 3.1 on 2020-12-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201207_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='max_backlog',
            field=models.IntegerField(default=0),
        ),
    ]
