# Generated by Django 3.1 on 2021-02-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_offer_max_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bio_keyword',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(default=2021),
        ),
    ]
